### ISSUE TITLE
downloaded png file is corrupt with ecp-curl

### ISSUE THREAD

**Issue by satyamohapatra-ml** [duncanmmacleod/ciecplib#99] opened 2022-06-06 21:11 UTC
After generating a valid proxy certificate, please try this:

ecp-curl -i "LIGO Scientific Collaboration" -k   -c "/tmp/ecpcookie.u40958" https://ldas-jobs.ligo-wa.caltech.edu/~detchar/monitor/H1-GRD_ISC_LOCK-0-43200.png  -o test.png

The output file is corrupted and not a png file. Text file don't have that problem.  The issue with the ecp-cookie-init script from ciecplib. 

Please see these two tickets for reference:

https://git.ligo.org/computing/helpdesk/-/issues/2277

https://git.ligo.org/computing/helpdesk/-/issues/2320

**Comment by duncanmmacleod** [comment] 2022-06-06 21:13
This is a duplicate of #98 (by one minute!).

**Closed** 2022-06-06 21:16 UTC
